server:
  contextPath:
  port: 9000

logging:
  file: ir-iiif-service.log
  level:
    edu.tamu.iiif: INFO
    org.springframework: INFO
  path: /var/logs/iiif

# to enable messaging, include profile weaver-messaging and update activemq broker-url, username and password

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: username
    password: password
  redis:
    host: localhost
    port: 6379
  profiles:
    active: production
    include: dspace, fedora

messaging:
  channels:
    cap: cap

iiif:
  admins:
    -
      username: admin
      password: abc123
  service:
    url: http://localhost:${server.port}${server.contextPath}
    connection:
      timeout: 1200000
      timeToLive: 1200000
      request.timeout: 600000
    socket.timeout: 1800000
  image.server.url: http://localhost:8182/iiif/2
  logo.url: https://brandguide.tamu.edu/assets/downloads/logos/TAM-Logo.png
  dspace:
    label-precedence:
    - "http://purl.org/dc/elements/1.1/title"
    - "http://purl.org/dc/terms/title"
    - "http://www.w3.org/2000/01/rdf-schema#label"
    - "http://purl.org/dc/elements/1.1/identifier"
    description-precedence:
    - "http://purl.org/dc/terms/abstract"
    - "http://purl.org/dc/terms/description"
    - "http://purl.org/dc/elements/1.1/description"
    metadata-prefixes:
    - "http://purl.org/dc/elements/1.1/"
    - "http://purl.org/dc/terms/"
    url: http://localhost:8080
    identifier: dspace
    webapp: xmlui
  fedora:
    label-precedence:
    - "http://purl.org/dc/elements/1.1/title"
    - "http://purl.org/dc/terms/title"
    - "http://www.w3.org/2000/01/rdf-schema#label"
    - "http://purl.org/dc/elements/1.1/identifier"
    description-precedence:
    - "http://purl.org/dc/terms/abstract"
    - "http://purl.org/dc/terms/description"
    - "http://purl.org/dc/elements/1.1/description"
    metadata-prefixes:
    - "http://purl.org/dc/elements/1.1/"
    - "http://purl.org/dc/terms/"
    url: http://localhost:9000/fcrepo/rest
    identifier: fedora
