server:
  contextPath:
  port: 9003

logging:
  file: ir-iiif-service.log
  level:
    edu.tamu.iiif: INFO
    org.springframework: INFO

spring.redis:
  host: localhost
  port: 6379
  profiles:
    active: production
    include: dspace-rdf, fedora-pcdm

iiif:
  service:
    url: http://localhost:${server.port}${server.contextPath}
    connection:
      timeout: 30000
      request.timeout: 15000
    socket.timeout: 60000
  image.server.url: http://localhost:8182/iiif/2
  logo.url: https://brandguide.tamu.edu/assets/downloads/logos/TAM-Logo.png
  dspace:
    url: http://localhost:8080
    webapp: xmlui
    identifier: 
      dspace-rdf: dspace-rdf
      dspace-rest: dspace-rest
  fedora:
    url: http://localhost:9000/fcrepo/rest
    pcdm.ext.url: http://localhost:9107/pcdm
    identifier:
      fedora-pcdm: fedora-pcdm
      fedora: fedora
