server:
  contextPath:
  port: 9000

logging:
  file: ir-iiif-service.log
  level:
    edu.tamu.iiif: INFO
    org.springframework: INFO
  path: /var/logs/iiif

spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: production
    include: dspace, fedora

iiif:
  admins:
    -
      username: admin
      password: abc123
  service:
    url: http://localhost:${server.port}${server.contextPath}
    connection:
      timeout: 1200000
      timeToLive: 1200000
      request.timeout: 600000
    socket.timeout: 1800000
  image.server.url: https://api-pre.library.tamu.edu/iiif/2
  logo.url: https://brandguide.tamu.edu/assets/downloads/logos/TAM-Logo.png
  dspace:
    url: https://dspacepre1.library.tamu.edu
    webapp: 
    identifier: 
      dspace-rdf: dspace
  fedora:
    url: https://api-pre.library.tamu.edu/fcrepo/rest
    identifier:
      fedora-pcdm: fedora